name: Aaz on software
description: Blogging about tech stuff
meta_description: Blogging about tech stuff

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: / # Doesn't work in placeholders - {{site.baseurl}} => ''
domain_name: 'https://andrykonchin.github.io'
google_analytics: 'UA-141523137-1'
google_analytics_4: 'G-3WLND6HE7S'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://andrykonchin.github.io'
author:         'Andrew Konchin'
