# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rails", "~>4.2"
gem "pg", ">= 0.18", "< 1.0"

group :test do
  gem "rspec-rails"
  gem "database_cleaner"
end
