source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'

group :test do
  gem "rspec-rails"
  gem "database_cleaner"
end

